spring:
  application:
    name: Flood API
  datasource:
    url: jdbc:sqlite:src/main/resources/db/flood.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true #Helps with SQLite tables having uppercase names