spring:
  application:
    name: Flood API
  datasource:
    #url: jdbc:sqlite:flood-data/service/src/main/resources/db/flood.db
    url: jdbc:sqlite:flood-data/service/src/main/resources/db/flood.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true #Helps with SQLite tables having uppercase names